# Stocks

In [ ]:
# Financial Data 
import yfinance as yf
# Date and Time
import datetime as dt

In [19]:
# Get the data for the stock AAPL, MSFT and GOOG
df = yf.download(['NVDA', 'AAPL', 'GOOG'], period = "1d", interval="1m")

[*********************100%***********************]  3 of 3 completed

In [20]:
df

Price                       Adj Close                               Close  \
Ticker                           AAPL        GOOG        NVDA        AAPL
Datetime
2024-12-06 14:30:00+00:00  242.929993  173.676407  144.300095  242.929993
2024-12-06 14:31:00+00:00  242.594101  173.789993  144.339996  242.594101
2024-12-06 14:32:00+00:00  242.199997  174.160004  145.310104  242.199997
2024-12-06 14:33:00+00:00  242.320007  174.339996  145.309998  242.320007
2024-12-06 14:34:00+00:00  242.399994  174.210007  145.531693  242.399994
...                               ...         ...         ...         ...
2024-12-06 20:55:00+00:00  242.699997  176.539993  142.350006  242.699997
2024-12-06 20:56:00+00:00  242.690002  176.514999  142.345001  242.690002
2024-12-06 20:57:00+00:00  242.669998  176.559998  142.360504  242.669998
2024-12-06 20:58:00+00:00  242.710007  176.529999  142.384995  242.710007
2024-12-06 20:59:00+00:00  242.860001  176.419998  142.399994  242.860001

Price                                                    High              \
Ticker                           GOOG        NVDA        AAPL        GOOG
Datetime
2024-12-06 14:30:00+00:00  173.676407  144.300095  243.020004  174.009995
2024-12-06 14:31:00+00:00  173.789993  144.339996  243.050003  174.470001
2024-12-06 14:32:00+00:00  174.160004  145.310104  242.619995  174.350006
2024-12-06 14:33:00+00:00  174.339996  145.309998  242.500000  174.602600
2024-12-06 14:34:00+00:00  174.210007  145.531693  242.500000  174.589996
...                               ...         ...         ...         ...
2024-12-06 20:55:00+00:00  176.539993  142.350006  242.940002  176.589996
2024-12-06 20:56:00+00:00  176.514999  142.345001  242.850006  176.550003
2024-12-06 20:57:00+00:00  176.559998  142.360504  242.759995  176.585007
2024-12-06 20:58:00+00:00  176.529999  142.384995  242.779999  176.610001
2024-12-06 20:59:00+00:00  176.419998  142.399994  242.899994  176.589996

Price                                         Low                          \
Ticker                           NVDA        AAPL        GOOG        NVDA
Datetime
2024-12-06 14:30:00+00:00  144.880005  242.690002  173.550003  144.270004
2024-12-06 14:31:00+00:00  144.690002  242.580002  173.639999  144.175003
2024-12-06 14:32:00+00:00  145.389999  242.139999  173.710007  144.259995
2024-12-06 14:33:00+00:00  145.449997  242.080002  174.130005  144.960007
2024-12-06 14:34:00+00:00  145.649994  242.182693  173.970001  145.210007
...                               ...         ...         ...         ...
2024-12-06 20:55:00+00:00  142.399994  242.565002  176.259995  142.125000
2024-12-06 20:56:00+00:00  142.369995  242.199997  176.436005  142.240005
2024-12-06 20:57:00+00:00  142.380005  242.619995  176.500000  142.270004
2024-12-06 20:58:00+00:00  142.399994  242.654999  176.509995  142.289993
2024-12-06 20:59:00+00:00  142.479996  242.630005  176.404999  142.320007

Price                            Open                           Volume  \
Ticker                           AAPL        GOOG        NVDA     AAPL
Datetime
2024-12-06 14:30:00+00:00  242.869995  173.869995  144.630005  1177906
2024-12-06 14:31:00+00:00  242.949997  173.639999  144.285004   167947
2024-12-06 14:32:00+00:00  242.580002  173.750000  144.339996   155814
2024-12-06 14:33:00+00:00  242.199997  174.195007  145.312698   144898
2024-12-06 14:34:00+00:00  242.320007  174.321106  145.300003    86622
...                               ...         ...         ...      ...
2024-12-06 20:55:00+00:00  242.595001  176.270004  142.125000   570072
2024-12-06 20:56:00+00:00  242.695007  176.550003  142.359207   319574
2024-12-06 20:57:00+00:00  242.690002  176.514999  142.350006   276410
2024-12-06 20:58:00+00:00  242.669998  176.554993  142.369995   363376
2024-12-06 20:59:00+00:00  242.710007  176.535004  142.384995  1189778

Price
Ticker                       GOOG      NVDA
Datetime
2024-12-06 14:30:00+00:00  406791  13290439
2024-12-06 14:31:00+00:00   98773    862446
2024-12-06 14:32:00+00:00   61848   1445256
2024-12-06 14:33:00+00:00   65864    904674
2024-12-06 14:34:00+00:00   46693    924313
...                           ...       ...
2024-12-06 20:55:00+00:00  143639   1040124
2024-12-06 20:56:00+00:00   63735    495506
2024-12-06 20:57:00+00:00   92490    594087
2024-12-06 20:58:00+00:00  135637    831502
2024-12-06 20:59:00+00:00  524433   2460009

[390 rows x 18 columns]

In [21]:
df.columns

MultiIndex([('Adj Close', 'AAPL'),
            ('Adj Close', 'GOOG'),
            ('Adj Close', 'NVDA'),
            (    'Close', 'AAPL'),
            (    'Close', 'GOOG'),
            (    'Close', 'NVDA'),
            (     'High', 'AAPL'),
            (     'High', 'GOOG'),
            (     'High', 'NVDA'),
            (      'Low', 'AAPL'),
            (      'Low', 'GOOG'),
            (      'Low', 'NVDA'),
            (     'Open', 'AAPL'),
            (     'Open', 'GOOG'),
            (     'Open', 'NVDA'),
            (   'Volume', 'AAPL'),
            (   'Volume', 'GOOG'),
            (   'Volume', 'NVDA')],
           names=['Price', 'Ticker'])

In [ ]:
# Closing prices
df['Close']

Ticker                           AAPL        GOOG        NVDA
Datetime
2024-12-06 14:30:00+00:00  242.929993  173.676407  144.300095
2024-12-06 14:31:00+00:00  242.594101  173.789993  144.339996
2024-12-06 14:32:00+00:00  242.199997  174.160004  145.310104
2024-12-06 14:33:00+00:00  242.320007  174.339996  145.309998
2024-12-06 14:34:00+00:00  242.399994  174.210007  145.531693
...                               ...         ...         ...
2024-12-06 20:55:00+00:00  242.699997  176.539993  142.350006
2024-12-06 20:56:00+00:00  242.690002  176.514999  142.345001
2024-12-06 20:57:00+00:00  242.669998  176.559998  142.360504
2024-12-06 20:58:00+00:00  242.710007  176.529999  142.384995
2024-12-06 20:59:00+00:00  242.860001  176.419998  142.399994

[390 rows x 3 columns]

In [27]:
# Get the current date and time
filename = dt.datetime.now()
# Create a string from the current date and time
filename = filename.strftime("%Y%m%d_%H%M%S") 
filename = '../data/stocks/' + filename + ".csv"

# Show the filename
filename

'../data/stocks/20241207_190612.csv'

In [29]:
# Save the data to a CSV file
df['Close'].to_csv(filename)

# End